version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 5080:80
        volumes:
            - "$pwd:/var/www/html:ro"
        networks:
            - webapp-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - webapp-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    webapp-network:
