version: "3.8"
services:
    web:
        image: sens31/demobgapp-web
        ports:
            - 5080:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: sens31/demobgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
